package com.feylabs.tahfidz.ViewModel

import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData
import androidx.lifecycle.ViewModel

class SurahViewModel : ViewModel() {
    var s = mutableListOf<String>()
    val surahIndex = MutableLiveData<MutableList<String>>()
    val surahMap = MutableLiveData<MutableMap<Int,String>>()

    fun addSurat() {
        s.add("Al-Fatihah")
        s.add("Al-Baqoroh")
        s.add("Ali-Imran")
        s.add("An-Nisaa")
        s.add("Al-Maa-idah")
        s.add("Al-An'aam")
        s.add("Al-A'raaf")
        s.add("Al-Anfaal")
        s.add("At-Taubah")
        s.add("Yunus")
        s.add("Hud")
        s.add("Ar-Ra'd")
        s.add("Ibrahim")
        s.add("Al-Hijr")
        s.add("An-Nahl")
        s.add("Al-Isra")
        s.add("Al-Kahfi")
        s.add("Maryam")
        s.add("Thaha")
        s.add("Al-Anbiyaa")
        s.add("Al-Hajj")
        s.add("Al-Mu'minuun")
        s.add("An-Nuur")
        s.add("Al-Furqaan")
        s.add("Asy-Syu'araa'")
        s.add("An-Naml")
        s.add("Al-Qashash")
        s.add("Al-Ankabut")
        s.add("Ar-Ruum")
        s.add("Luqman")
        s.add("As-Sajadah")
        s.add("Al-Ahzab")
        s.add("Saba")
        s.add("Faathir")
        s.add("Yaa Siin")
        s.add("Ash-Shaffaat")
        s.add("Shaad")
        s.add("Az-Zumar")
        s.add("Al-Mu'min")
        s.add("Fush Shilat")
        s.add("Asy-Syuura")
        s.add("Az-Zukhruf")
        s.add("Ad-Dukhaan")
        s.add("Al-Jaatsiyah")
        s.add("Al-Ahqaaf")
        s.add("Muhammad")
        s.add("Al-Hujurat")
        s.add("Qaaf")
        s.add("Adz-Dzaariyaat")
        s.add("Ath-Thuur")
        s.add("An-Najm")
        s.add("Al-Qamar")
        s.add("Ar-Rahmaan")
        s.add("Al-Waaqiah")
        s.add("Al-Hadiid")
        s.add("Al-Mujaadilah")
        s.add("Al-Hasyr")
        s.add("Al-Mumtahanah")
        s.add("Ash-Shaff")
        s.add("Al-Jumu'ah")
        s.add("Al-Munaafiquun")
        s.add("At-Taghaabun")
        s.add("Ath-Thalaaq")
        s.add("At-Tahrim")
        s.add("Al-Mulk")
        s.add("Al-Qalam")
        s.add("Al-Haaqqah")
        s.add("Al-Ma'aarij")
        s.add("Nuh")
        s.add("Al-Jin")
        s.add("Al-Muzzammil")
        s.add("Al-Muddatstsir")
        s.add("Al-Qiyaamah")
        s.add("Al-Insaan")
        s.add("Al-Mursalaat")
        s.add("An-Naba")
        s.add("An-Naazi'aat")
        s.add("'Abasa")
        s.add("At-Takwir")
        s.add("Al-Infithar")
        s.add("Al-Muthaffifiin")
        s.add("Al-Insyiqaaq")
        s.add("Al-Buruuj")
        s.add("Ath-Thaariq")
        s.add("Al-A'laa")
        s.add("Al-Ghaasyiyah")
        s.add("Al-Fajr")
        s.add("Al-Balad")
        s.add("Asy-Syams")
        s.add("Al-Lail")
        s.add("Ad-Dhuhaa")
        s.add("Alam-Nasyrah")
        s.add("At-Tiin")
        s.add("Al-'Alaq")
        s.add("Al-Qadar")
        s.add("Al-Bayyinah")
        s.add("Al-Zalzalah")
        s.add("Al-'Aadiyaat")
        s.add("Al-Qaari'ah")
        s.add("At-Takaatsur")
        s.add("Al-'Ashr")
        s.add("Al-Humazah")
        s.add("Al-Fiil")
        s.add("Al-Quraisy")
        s.add("Al-Maa'un")
        s.add("Al-Kautsar")
        s.add("Al-Kaafiruun")
        s.add("An-Nashr")
        s.add("Al-Lahab")
        s.add("Al-Ikhlash")
        s.add("Al-Falaq")
        s.add("An-Naas")
    }
    
    fun getMapSurah() : LiveData<MutableMap<Int,String>>{
        s.clear()
        addSurat()
        var tempMap = mutableMapOf<Int,String>()

        for (i in 1  until s.size){
            tempMap[i+1] = s[i]
        }
        surahMap.postValue(tempMap)
        return surahMap
    }

    fun getSurahList() : LiveData<MutableList<String>>{
        s.clear()
        addSurat()
        surahIndex.postValue(s)
        return surahIndex
    }



}